# Generated by Django 5.1.3 on 2024-11-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpricing',
            name='ticket_type',
            field=models.CharField(choices=[('general', 'General'), ('vip', 'VIP'), ('early_bird', 'Early Bird')], max_length=100, unique=True),
        ),
    ]
