# Generated by Django 5.1.3 on 2024-11-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_remove_event_price_early_bird_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
    ]
