# Generated by Django 5.1.3 on 2024-12-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0010_alter_ticket_attendee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price_early_bird',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price_general',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
