# Generated by Django 5.1.3 on 2024-12-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0011_alter_ticket_price_early_bird_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tickets_available',
            field=models.IntegerField(default=0),
        ),
    ]
